# Generated by Django 2.2.5 on 2019-09-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.CharField(default=None, max_length=30, unique=True)),
                ('name', models.CharField(default=None, max_length=60)),
                ('data', models.CharField(default=None, max_length=30)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(default=None, max_length=30, unique=True)),
                ('name', models.CharField(default=None, max_length=60)),
                ('location', models.CharField(default=None, max_length=60)),
                ('sensors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sensor')),
            ],
        ),
    ]
