# Generated by Django 2.2.5 on 2019-09-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default=None, max_length=30)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='date',
        ),
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensorData',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.SensorData'),
        ),
    ]
