# Generated by Django 2.2.5 on 2019-09-17 05:27

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190916_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=djongo.models.fields.EmbeddedModelField(model_container='Sensor', null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensorData',
            field=djongo.models.fields.EmbeddedModelField(model_container='SensorData', null=True),
        ),
    ]
