# Generated by Django 2.2.5 on 2019-09-17 05:55

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190917_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=djongo.models.fields.EmbeddedModelField(model_container=api.models.Sensor, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensorData',
            field=djongo.models.fields.EmbeddedModelField(model_container=api.models.SensorData, null=True),
        ),
    ]
